pipeline {
    agent any

    tools {
        nodejs "Node"
    }

    environment {
        registryCredential = 'ecr:eu-west-1:awscreds'
        appRegistry = "677276091734.dkr.ecr.eu-west-1.amazonaws.com/lamp-stack-frontend"
        frontendRegistry = "https://677276091734.dkr.ecr.eu-west-1.amazonaws.com"
        cluster = 'frontend-cluster'
        service = 'frontend-cluster-service'
    }

    stages {
        stage('Fetch code') {
            steps {
                git branch: 'main', url: 'https://github.com/BINAH25/react-crud-php-api-mysql.git'
            }
        }

        stage('Check for frontend changes') {
            steps {
                script {
                    def changedFiles = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim()
                    def frontendChanged = changedFiles.split("\n").any { it.startsWith("frontend/") }
                    
                    if (!frontendChanged) {
                        echo "No changes detected in frontend. Skipping build."
                        currentBuild.result = 'SUCCESS'
                        error("Skipping remaining stages.")  // Stop pipeline execution
                    } else {
                        echo "Changes detected in frontend. Proceeding with the build."
                    }
                }
            }
        }

        stage('SonarQube analysis') {
            environment {
                scannerHome = tool 'sonar4.7'
            }
            steps {
                withSonarQubeEnv('sonar') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }

        stage('Buid App Image') {
            steps {
                script {
                    dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "./frontend/")
                }
            }
        }


        stage('Scan Image with Trivy') {
            steps {
                script {
                    sh """
                        trivy image --format table --severity HIGH,CRITICAL ${appRegistry}:$BUILD_NUMBER || exit 1
                    """
                }
            }
        }


        stage('Upload Image to ECR') {
            steps {
                script {
                    docker.withRegistry( frontendRegistry, registryCredential ){
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy to ecs') {
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}
